const ColorPalette = {
  primary: "#007ACC",
  secondary: "#1479B9",
  thirdry: "#DFEFF9",
  accent: "#B65F2C",
  success: "#4CAF50",
  successBackground: "#3C8C40",
  toggleBackground: "#f8f9fa",
  background: "white",
  selected: "#9bd0f3ff",
  men: "#0060a1",
  women: "#9B0000",
  text: "#212121",
  muted: "#e0e0e0",
  disabled: "#aaa7a7ff",
  error: "#FF0000",
  whiteText: "white",
  blackText: "black",
  cardBackGround: "#f9d713",
  progress: "#FFC107",
  cardShadow: "#000",
  badgeBackground: "black",
  badgeText: "white",
  emptyText: "#999",
  checkboxBorder: "white",
  toggleBorder: "#999",
  remove: "#FF6B6B",
  sectionTitie: "#333",
  danger: "#F44336",
  normalIcon: "black",
  whiteIcon: "#f0f0f0",
  restIcon: "#edab12",
  link: "#007AFF",
  accessoryBackground: "#f2f2f2",
  accessoryborderColor: "#ccc",
  borderline: "#ccc",
  toggleCircle: "white",
  playerTabelHeader: "#c4c4c4",
  restPlayerBackground: "#FFF9E6",
  restPlayerBorder: "#FFE8B2",
  restPlayerName: "#664500",
  swapBorder: "#cc7838",
  editRestBackground: "#ccc4c4",
  inputBorder: "#ddd",
  transparent: "rgba(0,0,0,0.3)",
  filterItemName: "#666",
  filterItemBg: "#f0f0f0",
  filterItemCancel: "#888888",
  dark: {
    background: "#121212",
    text: "#FFFFFF",
  },
  separator: "#eee",
};

export default ColorPalette;
